name: gha-result
on:
  workflow_dispatch:
  push:
    branches:
    - branch-1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Set up cache
      uses: actions/cache@v3.3.1
      with:
        path: "${{ github.workspace }}/.m2/repository"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: '8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: chmod +x mvnw
    - run: sudo redis-server /etc/redis/redis.conf --port 6379
    - run: "./mvnw -q test"
    - run: bash <(curl -s https://codecov.io/bash)
      if: "${{ success() }}"
