matrix:
  language: java
  java
  os: ubuntu-latest

name: placeholder_Name

on:
  pull_request
  push:
    branches:
    - branch-2

jobs:
  build:
    strategy:
      matrix: java
      fail-fast: FALSE
  - name: Placeholder
    runs-on: ubuntu-latest
    steps:
      with: path
      with:
        java-version:
          ${{ matrix.java }}
          1.8
      with: key
      with: java-version
      uses: actions/checkout@version
      uses: actions/setup-java@version
    - name: set up jdk 1.8
      with:
        path: ~/.maven-
        key: ${{ runner.os }}-maven-${{ hashfiles(arg) }}
      uses: actions/cache@version
      run:
        bash <(curl -s https://codecov.io/bash)
        ./mvnw -q test
        chmod +x mvnw

macos:
  jdk: openjdk8

