name: Manual Migration Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: chmod command execute script
        run: chmod +x mvnw

      - name: run tests
        run: ./mvnw -q test -Dmaven=3.9.6

      - name: code coverage upload
        if: success()
        run: bash <(curl -s https://codecov.io/bash)

      - name: cached maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2


      


        