name: Manual Migration Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!