name: Manual Migration Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: chmod command execute script
        run: chmod +x mvnw

      - name: Run Maven Wrapper to update or download
        run: ./mvnw -N io.takari:maven:wrapper -Dmaven=3.9.6

      - name: Set executable permissions for mvn
        run: chmod +x .mvn/wrapper/dists/apache-maven-3.9.6-bin/2p3i4d0ctslqhqbi931o6l1k27/apache-maven-3.9.6/bin/mvn


      - name: code coverage upload
        if: success()
        run: bash <(curl -s https://codecov.io/bash)

      


      


        